site_name: Estadísticas con python
site_description: A website template for using mkdocs
site_author: Corina Navarrete
site_url: https://corinanm.github.io/statistics-python

repo_url: https://github.com/CorinaNM/statistics-python

copyright: "Copyright &copy; 2024 Corina Navarrete"

theme:
  palette:
    - scheme: default
      #   primary: blue
      #   accent: indigo
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  name: material
  icon:
    repo: fontawesome/brands/github
  features:
    - navigation.instant
    - search.highlight
  custom_dir: "docs/overrides"
  font:
    text: Google Sans
    code: Regular

plugins:
  - search
  - mkdocstrings
  - git-revision-date
  - mkdocs-jupyter:
      include_source: True
      ignore_h1_titles: True
      execute: false
      allow_errors: false
      ignore: ["name.ipynb"]
      execute_ignore: ["path/*.ipynb"]

markdown_extensions:
  - attr_list
  - toc:
      permalink: true

extra:
  analytics:
    provider: google
    property: G-XXX

nav:
  - Home: index.md
  - Notebook:
      - template.ipynb
  - Chapter 1:
      - chapter_01/intro.ipynb
      - chapter_01/basemaps.ipynb
  - Chapter 2:
      - chapter_02/colorbar.ipynb
      - chapter_02/heatmap.ipynb
  - Blog: https://blog.gishub.org
  - YouTube Channel: https://youtube.com/@giswqs
  - Report Issues: https://github.com/giswqs/mkdocs-template/issues
